# Configfile for MobCounterPlugin
version: 1
# Max Scan Radius
scan-radius: 128

# Header, for Groups %radius% will be in there Minecraft Colorcodes can be used here
header: "Entitys in Scanradius of %radius% Blocks:"
no-entities-found: "No Entities in %radius% Blocks could be found."
# Definition of Groups Minecraft Colorcodes can be used here
groups:
  group1:
    name: "Armorstands and Displays"
    color: "RED"
    entities:
      - ARMOR_STAND
      - BLOCK_DISPLAY
      - ITEM_DISPLAY
      - ITEM_FRAME

  group2:
    name: "Animals and Monsters"
    color: "GREEN"
    entities:
      - ALLAY
      - AXOLOTL
      - BAT
      - BEE
      - BLAZE
      - CAMEL
      - CAT
      - CAVE_SPIDER
      - CHICKEN
      - COD
      - COW
      - CREEPER
      - DOLPHIN
      - DONKEY
      - DROWNED
      - ELDER_GUARDIAN
      - ENDER_DRAGON
      - ENDERMAN
      - ENDERMITE
      - EVOKER
      - FOX
      - FROG
      - GHAST
      - GIANT
      - GLOW_SQUID
      - GOAT
      - GUARDIAN
      - HOGLIN
      - HORSE
      - HUSK
      - ILLUSIONER
      - IRON_GOLEM
      - LLAMA
      - MAGMA_CUBE
      - MOOSHROOM
      - MULE
      - OCELOT
      - PANDA
      - PARROT
      - PHANTOM
      - PIG
      - PIGLIN
      - PIGLIN_BRUTE
      - PILLAGER
      - POLAR_BEAR
      - PUFFERFISH
      - RABBIT
      - RAVAGER
      - SALMON
      - SHEEP
      - SHULKER
      - SILVERFISH
      - SNIFFER
      - SKELETON
      - SKELETON_HORSE
      - SLIME
      - SNOW_GOLEM
      - SPIDER
      - SQUID
      - STRAY
      - STRIDER
      - TADPOLE
      - TRADER_LLAMA
      - TROPICAL_FISH
      - TURTLE
      - VEX
      - VILLAGER
      - VINDICATOR
      - WANDERING_TRADER
      - WARDEN
      - WITCH
      - WITHER
      - WITHER_SKELETON
      - WOLF
      - ZOGLIN
      - ZOMBIE
      - ZOMBIE_HORSE
      - ZOMBIE_VILLAGER
      - ZOMBIFIED_PIGLIN


  group3:
    name: "Other Entitys"
    color: "YELLOW"
    entities: []  # Optional
