# Configfile for MobCounterPlugin
version: 1
# Radius around the Players to check for Entitys
scan-radius: 128

# Header, thats used by Groupoutput. Placeholder %radius% will be used to output scan-radius
header: "Entitys im Scanbereich von %radius% Blöcken:"

# Definition of Groups to Scan for and Chatouput
group:
  group1:
    name: "Armorstands und Anzeigen"
    color: "RED"
    entities:
      - ARMOR_STAND
      - BLOCK_DISPLAY
      - ITEM_DISPLAY
      - ITEM_FRAME

  group2:
    name: "Tiere und Monster"
    color: "GREEN"
    entities:
      - COW
      - SHEEP
      - PIG
      - CHICKEN
      - ZOMBIE
      - SKELETON
      - CREEPER
      - SPIDER
      - ENDERMAN

  group3:
    name: "Andere Entitys"
    color: "YELLOW"
    entities: []  # Optional: Define other Entities here
