name: MobCounterPlugin
main: de.blockminers.mobcounter.MobCounterPlugin
version: 1.0
api-version: 1.21.1
commands:
  mcpmobs:
    description: Counts all Entities in an Area.
    usage: /mobs
  mcpreload:
    description: Reloads the Config.
